
services:
  # PostgreSQL Database
  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: dixitkasodariya
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dixitkasodariya -d authdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  # Spring Boot Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: dixitkasodariya
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: change_this_in_env_but_do_not_use_in_prod
      JWT_EXPIRATION_MS: 3600000
    ports:
      - "4000:4000"
    networks:
      - microservices-network

  booking-db:
    image: postgres
    container_name: booking-db
    restart: always
    environment:
      POSTGRES_USER: dixitkasodariya
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookingdb
    volumes:
      - booking_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # Expose on host port 5433 to avoid conflict with auth-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dixitkasodariya -d bookingdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  # Spring Boot booking Service
  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    restart: always
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-db:5432/bookingdb
      SPRING_DATASOURCE_USERNAME: dixitkasodariya
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: change_this_in_env_but_do_not_use_in_prod
      JWT_EXPIRATION_MS: 3600000
    ports:
      - "4001:4001"
    networks:
      - microservices-network

volumes:
  auth_pgdata:
  booking_pgdata:

networks:
  microservices-network:
    driver: bridge