
services:
  # PostgreSQL Database
  db:
    image: postgres
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: dixitkasodariya
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dixitkasodariya -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

  # 🚀 Spring Boot Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/authdb
      SPRING_DATASOURCE_USERNAME: dixitkasodariya
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: change_this_in_env_but_do_not_use_in_prod
      JWT_EXPIRATION_MS: 3600000
    ports:
      - "4000:4000"
    networks:
      - auth-network

volumes:
  pgdata:

networks:
  auth-network:
    driver: bridge